language: go
go: 
  - 1.8
  - 1.9

before_install:
  # Install Glide
  - mkdir -p "${GOPATH}/bin"
  - curl https://glide.sh/get | bash

cache:
  directories:
  - vendor

script:
  - glide i
  - make test
  - make build